config/routes.rb
Rails.application.routes.draw do

  resources :maps, only: [:show] do
    member do
      put :move
      put :restart
    end
  end

  namespace :api do
    namespace :v1 do
      resources :taxis, only: [:create, :show]
      resources :passengers, only: [:create, :show]

      resources :maps, only: [:create, :show, :index] do
        member do
          put :move
          put :restart
          get :detail
        end
      end
    end
  end
end

app/models/map.rb
# == Schema Information
#
# Table name: maps
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  rows       :integer          not null
#  cols       :integer          not null
#  time       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Map < ActiveRecord::Base
  has_many :blocks , class_name: 'MapBlock'
  has_many :taxis
  has_many :passengers
end

app/models/map_block.rb
# == Schema Information
#
# Table name: map_blocks
#
#  id         :integer          not null, primary key
#  row        :integer          not null
#  col        :integer          not null
#  map_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MapBlock < ActiveRecord::Base
  belongs_to :map

  def position=(position)
    self.row = position.row
    self.col = position.col
  end

  def position
    Position.new(row, col)
  end  
end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  map_id     :integer
#  row        :integer          not null
#  col        :integer          not null
#  dest_row   :integer          not null
#  dest_col   :integer          not null
#  status     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Passenger < ActiveRecord::Base
  belongs_to :taxi
  belongs_to :map

  enum status: [:calling, :waiting, :going]

  scope :not_going, -> { where("status <> ?", Passenger.statuses[:going]) }
end

app/models/taxi.rb
# == Schema Information
#
# Table name: taxis
#
#  id           :integer          not null, primary key
#  name         :string           not null
#  passenger_id :integer
#  status       :integer          not null
#  row          :integer          not null
#  col          :integer          not null
#  map_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Taxi < ActiveRecord::Base
  has_one :passenger, autosave: true
  belongs_to :map

  enum status: [:empty, :going, :full]
end

app/controllers/api/v1/maps_controller.rb
module Api::V1
  class MapsController < ApplicationController
    respond_to :json

    def create
      respond Map::Operation::Create, params: create_params, namespace: [:api, :v1]
    end

    def index
      respond Map::Operation::List
    end

    def show
      respond_with present Map::Operation::Show
    end

    def detail
      respond Map::Operation::Detail
    end

    def move
      respond Map::Operation::Move
    end

    def restart
      respond Map::Operation::Restart
    end

    def create_params
      params.permit(:name, :file)
    end
  end
end

app/controllers/api/v1/passengers_controller.rb
module Api::V1
  class PassengersController < ApplicationController
    respond_to :json

    def create
      respond Passenger::Operation::Create, params: create_params, namespace: [:api, :v1]
    end

    def show
      respond_with present Passenger::Operation::Show
    end

    def create_params
      params.permit(:name, :row, :col, :dest_row, :dest_col, :map_id)
    end
  end
end

app/controllers/api/v1/taxis_controller.rb
module Api::V1
  class TaxisController < ApplicationController
    respond_to :json

    def create
      respond Taxi::Operation::Create, params: create_params, namespace: [:api, :v1]
    end

    def show
      respond_with present Taxi::Operation::Show
    end

    private

    def create_params
      params.permit(:name, :row, :col, :map_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Trailblazer::Operation::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  responders :json

  rescue_from 'ActiveRecord::RecordNotFound' do |exception|
    render json: {}, status: 404
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  respond_to :html

  def show
    respond Map::Operation::Detail
  end

  def move
    run Map::Operation::Move do |op|
      return redirect_to map_path(op.model.id)
    end
  end

  def restart
    run Map::Operation::Restart do |op|
      return redirect_to map_path(op.model.id)
    end
  end
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Cidade de Taxis - <%= yield(:title) %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Todos os Mapas <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Map.all.each do |map| %>
            <li> <%= link_to map.name, map_path(map) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <%= yield(:navbar) %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityTaxi</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "nav" %>
    <section>
    <%= yield %>
    </section>

    <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    </script>
  </body>
</html>

app/views/maps/_blocked_node.html.erb
<td class="danger"><span>&nbsp;</span></td>

app/views/maps/_node.html.erb
<td class="active">
  <% model.find_taxi(node.position).each do |taxi| %>
    <%= render "taxi", taxi: taxi %>
  <% end %>
  <% model.find_waiting_passenger(node.position).each do |passenger| %>
    <%= render "passenger", passenger: passenger %>
  <% end %>
</td>

app/views/maps/_passenger.html.erb
<a href="#" data-toggle="popover" data-content="<%= passenger.name %>">
  <span class="label label-info">P</span>
</a>

app/views/maps/_taxi.html.erb
<a href="#" data-toggle="popover" title="<%= taxi.name %>"
   data-content="<%= taxi.passenger.present? ? taxi.passenger.name : "(vazio)" %>">
  <span class="label label-default"><%= Taxi.statuses[taxi.status]  %></span>
</a>

app/views/maps/show.html.erb
<% content_for :title do %>
  <%= @model.name %>
<% end %>

<% content_for :navbar do %>
  <p class="navbar-text navbar-right">
    Tempo Atual: <span class="badge"><%= @model.time %></span>
  </p>

  <%= form_tag restart_map_path(@model.id), method: :put, class: "navbar-form navbar-right" do %>
    <button type="submit" class="btn btn-default" title="Reiniciar" >
      Reiniciar <span class="glyphicon glyphicon-repeat"></span>
    </button>
  <% end %>

  <%= form_tag move_map_path(@model.id), method: :put, class: "navbar-form navbar-right" do %>
    <button type="submit" class="btn btn-default" title="Avançar" >
      Avançar <span class="glyphicon glyphicon-play-circle"></span>
    </button>
  <% end %>
<% end %>

  <div class="panel panel-primary">
    <div class="panel-body">
      <table class="table table-bordered">
        <tr>
          <th></th>
          <% @model.cols.times do |col| %><td><%= col %></td><% end %>
        </tr>
        <% @model.rows.times do |row| %>
        <tr>
          <th scope="row"><%= row %></th>
          <% @model.cols.times do |col| %>
            <% node = @model[row, col] %>
            <% if node.blocked? %>
              <%= render "blocked_node" %>
            <% else %>
              <%= render "node", model: @model, node: node %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
  </div>